klaudsol/klaudsol-cms

- backend/models/core/Entity.js
- components/elements/frontPage/LoginForm.js
- components/elements/inner/AppSidebar.js
- components/klaudsolcms/AppButtonSpinner.js
- components/klaudsolcms/modals/AppInfoModal.js
- components/klaudsolcms/tables/AppContentManagerTable.js
- pages/admin/content-manager/[entity_type_slug]/[id].js
- pages/admin/content-manager/[entity_type_slug]/create.js
- pages/admin/content-manager/[entity_type_slug]/index.js
- pages/admin/plugins/content-type-builder/[entity_type_slug].js
Additional Updates:
- Fixed frontend issues (Content-Manager Page and Content Builder Page)
- Sidebar Fix 
- Fixed frontend for single page item on content manager page
- Additional UI / UX updates
> October 4 2022 - Updates

- backend/data_access/DB.js
- backend/models/core/Entity.js
- components/elements/inner/AppSidebar.js
- db/structure.sql
- pages/admin/content-manager/[entity_type_slug]/[id].js
- pages/admin/content-manager/[entity_type_slug]/create.js
- pages/api/[entity_type_slug]/[id].js
- pages/api/[entity_type_slug]/index.js
- Added function to create new entry
> Create new Entry 

- backend/models/core/Entity.js
- pages/admin/content-manager/[entity_type_slug]/[id].js
- pages/admin/content-manager/[entity_type_slug]/create.js
- pages/api/[entity_type_slug]/[id].js
- pages/api/[entity_type_slug]/index.js
- Fixed entries bug in create entry
- Working edit entry 
- Added loading skeleton to edit entry
> October 26 2022 updates

- components/klaudsolcms/modals/modal_body/CollectionTypeBody.js
Slugs are now auto lowercased when adding a new collection type
> [KlaudSolCMS-114] Fix: keep slugs lowercase#114

- components/klaudsolcms/modals/AddEditAnotherFieldModal.js
- styles/klaudsolcms.scss
Adjusted the width of input-boxes
> Klaudsol-Cms #124: Adjusted the width of input-boxes

- components/layouts/ContentTypeBuilderLayout.js
Added X-Axis padding in Content-Type-Builder.
> Added x-axis padding in Content-Type-Builder

- components/klaudsolcms/AppDropdown.js
- pages/admin/content-manager/[entity_type_slug].js
Remove the gear icon and the dropdown button as it doesn't have any function/s at the moment.
> Remove the gear icon and dropdown button

- components/elements/inner/sidebar/FullSidebar.js
> Klaudsol CMS Tasks #155

- backend/models/core/Entity.js
- components/reducers/entityReducer.js
- pages/admin/content-manager/[entity_type_slug]/[id].js
- pages/api/[entity_type_slug]/[id].js
1. changed the `[propertyType]` to `longValue` since it causes the `slug` to be undefined when receiving a string slug. It may not affect neither the frontend or backend since the undefined value is not being used due to some refactors. but it can cause confusion in the future.
note: both GET and PUT method are still working dynamically.
GET method:
by slug: `http://localhost:3001/api/menus/donut`
by id     `http://localhost:3001/api/menus/89`    
PUT method: 
by slug: `http://localhost:3001/api/menus/donut`
by id:     `http://localhost:3001/api/menus/89`
https://user-images.githubusercontent.com/109654448/216892777-9531900d-0b80-475f-9c99-a5001c909e59.mp4
.  changed and added 2 new data in `metadata`.  in the pre-existing code, the `entity_id` and `entity_type_id` are always equal. (bug) …
> [Klaudsol-CMS-#167] Update content does not save

- pages/admin/content-manager/[entity_type_slug]/[id].js
- pages/admin/content-manager/[entity_type_slug]/create.js
> [KlaudSol-CMS-#222] Temporarily Comment out these areas

- components/Util.js
- components/elements/inner/ContentManagerSubMenu.js
- components/reducers/actions.js
- components/reducers/rootReducer.js
- lib/actions.js
- pages/admin/content-manager/[entity_type_slug].js
- pages/admin/content-manager/[entity_type_slug]/[id].js
> [KlaudSol-CMS-#175] Should display the user-friendly content type name, not the slug

- .gitignore
- components/klaudsolcms/AppContentBuilderTable.js
> [KlaudSol-CMS-#225] No loading spinner when updating content type builder

- components/elements/frontPage/LoginForm.js
- styles/klaudsolcms.scss
> Staging => Main

- components/klaudsolcms/tables/AppContentManagerTable.js
- styles/klaudsolcms.scss
> [Klaudsol-CMS-#291] Update table format

- pages/admin/content-type-builder/[entity_type_slug].js
> [KlaudSol-CMS-#192] fix duplicated add collection type

- components/elements/inner/AppSidebar.js
- components/elements/inner/sidebar/FullSidebar.js
- components/reducers/actions.js
- pages/api/session.js
* Instead of populating content type on login (which is really strange and can get outdated really fast), we populate it in our rootState so that the changes will be instantaneous.
> Realtime content type

- pages/admin/me.js
The server expects camel case, but we are giving it snake case
> Fixed update password

- backend/models/core/Setting.js
- pages/admin/settings.js
- pages/api/settings.js
- pages/api/settings/[slug].js
- pages/api/settings/index.js
- This is just a quick and dirty fix so that we can upload the logo
- The whole settings page should be refactored. I've refactored it in PR (`#343`) but that would require adding additional columns on the database. Will be fixing this soon
> QUICK FIX - Refactored settings to cater to presigned URLS

- components/elements/inner/sidebar/FullSidebar.js
- yarn.lock
> Fixed sidebar highlighting

- backend/models/core/Entity.js
- components/EntityAttributeValue.js
- components/cmsTypes.js
- components/klaudsolcms/tables/AppContentManagerTable.js
- components/renderers/admin/AdminRenderer.js
- components/renderers/admin/BooleanRenderer.js
- constants/index.js
- db/migrations/202306070531900_add_value_boolean_to_values_table.json
- pages/_app.js
- pages/admin/content-manager/[entity_type_slug]/create.js
- styles/general.scss
- Added boolean attribute type
- Default value is false (if not checked)
- Added `value_boolean` type to `values` table 
- Only displays `Yes` or `No` in the table
Sample UI:
> Add boolean attribute type

- RELEASE.md
- package.json
- Updated RELEASE.md 
- Bump package.json to `3.6.0`
> Update release and bump package.json

- components/entity_types/SingleType.js
- Remove slug textbox 
- Fix bug on single type creation
> Fix Singleton bug

- components/attribute_types/RichTextAttributeType.js
- Add link to WYSIWYG Editor
Screenshots:
Sample API
> Add link to wysiwyg

- package.json
- pages/api/session.js
- yarn.lock
- Bumped klaudsol commons to `v1.8.1`
- Added `id` to token (The `id` is the `people_id`)
> Add people id to token

- backend/models/core/EntityType.js
- components/entity_types/SingleType.js
- components/klaudsolcms/modals/modal_body/EditCollectionTypeBody.js
- pages/admin/content-manager/[entity_type_slug]/index.js
- pages/admin/content-type-builder/[entity_type_slug].js
- styles/general.scss
- Removed `entries found` in Singleton Content Types
- Fixed edit content type modal (editing the variant is disabled)
> Singleton fixes

- backend/models/core/Entity.js
- components/EntityAttributeValue.js
- components/contexts/EntityContext.js
- components/reducers/createReducer.js
- components/reducers/entityReducer.js
- db/migrations/20230621102400_alter_entities_table_status.json
- db/migrations/20230621102700_add_published_status_to_all_entities.json
- lib/actions.js
- pages/admin/content-manager/[entity_type_slug]/[id].js
- pages/admin/content-manager/[entity_type_slug]/create.js
- pages/admin/content-manager/[entity_type_slug]/index.js
- pages/api/[entity_type_slug].js
- pages/api/[entity_type_slug]/[id].js
- styles/general.scss
- Line 180 - 351 in `/content-manager/[entity_type_slug]/create.js`:
- I just indented the block of code by two spaces
> Drafts feature

- package.json
- pages/api/session.js
- yarn.lock
- Bumped klaudsol/commons to `v1.8.1`
- Added `userId` to token
> Hotfix: Add people id to token
